version: '3.9'

services:
  app:
    build:
      context: ./app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - ALLOWED_HOSTS=0.0.0.0
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=user
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db

volumes:
  postgres_data:
